# app/config/security.yml
security:
    encoders:
        SW\UserBundle\Entity\User:
            algorithm: sha512
            iterations: 1
            encode_as_base64: false

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
            administrators:
                entity:
                    class: SWUserBundle:User
                    property: email


    firewalls:
        default:
            anonymous: ~
            form_login:
                login_path: /connexion
                check_path: /check
                provider:     administrators
                success_handler: redirect.after.login
            logout:
                path:   /deconnexion
                target: /
            remember_me:
                key:      "%secret%"
                lifetime: 2232000 
                path:     /
                domain:   ~ # Prend la valeur par défaut du domaine courant depuis $_SERVER

    access_control:
        - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/.*, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/administration, roles: ROLE_ADMIN }